export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";

export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const GET_POST_REQUEST = "GET_POST_REQUEST";

export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_POST_FAIL = "GET_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const CLEAR_UPDATE_STATUS = "CLEAR_UPDATE_STATUS";
