export const GET_USERS_LOADING = "GET_USERS_LOADING";

export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
